# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20200130_0711'),
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='caption',
            field=models.CharField(default='Ceat', max_length=50, verbose_name='Caption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'images/products/%Y/%m/', verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='partner',
            name='product_classes',
            field=models.ManyToManyField(blank=True, to='catalogue.ProductClass'),
        ),
        migrations.AddField(
            model_name='partner',
            name='value_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional Value'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delivery Charge'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='max_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max. Qty for a customer'),
        ),
    ]
