# Generated by Django 2.1.1 on 2020-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200325_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='uom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit of Measure'),
        ),
    ]
