# Generated by Django 2.1.1 on 2020-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20200130_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='pack_of',
            field=models.IntegerField(verbose_name="Pack of", default=1),
        ),
    ]
