# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='caption',
            field=models.CharField(default='Ceat', max_length=50, verbose_name='Caption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'images/products/%Y/%m/', verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
