# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20200130_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_role',
            field=models.CharField(blank=True, null=True, max_length=50),
            preserve_default=False,
        ),
    ]
