# Generated by Django 2.1.1 on 2020-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20200318_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_role',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Available For'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/products/%Y/%m/', verbose_name='Original'),
        ),
    ]
